consul:
  image: progrium/consul
  ports:
    - 53:53
    - 53:53/udp
    - 8300:8300
    - 8301:8301
    - 8301:8301/udp
    - 8400:8400
    - 8500:8500
  command: -node=consul -server -bootstrap -ui-dir /ui
    

registrator:
  image: gliderlabs/registrator:latest
  net: "host"
  volume: /var/run/docker.sock:/tmp/docker.sock
  command: /bin/registrator consul://consul:8500
  links:
   - consul


#haproxy:


#nginx:
